# Generated by Django 6.0.5 on 2026-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
