# Generated by Django 6.0.5 on 2026-06-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('BECE', 'BECE'), ('NORMAL', 'Normal School')], max_length=10)),
                ('mode', models.CharField(default='practice', max_length=20)),
                ('subject_names', models.JSONField(default=list)),
                ('question_ids', models.JSONField(default=list)),
                ('question_subject_map', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TIMED_OUT', 'Timed Out')], default='IN_PROGRESS', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('duration_minutes', models.IntegerField(default=35)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
