# Generated by Django 6.0.5 on 2026-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('BECE', 'BECE'), ('NORMAL', 'Normal School')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('BECE', 'BECE'), ('NORMAL', 'Normal School')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
    ]
